### ISSUE TITLE
Debug TS files not working in Chrome

### ISSUE THREAD

**Issue by Marty070** [antonybudianto/angular-starter#205]
Hi,

I've followed the setup steps in the readme. Everything works as expected, except when I select a .ts file in the Chrome debugger it shows up empty. It looks like that it has something to to with the source mapping, maybe a config issue?

*update* it does work when I manually change the js.map file, adding an extra '/' before the relative path to the .ts file. e.g. '{"version":3,"sources":["/app/todolist/todolist.component.ts"] ... however, when I restart npm start it will overwrite these changes. Any thoughts? Thanks!

**Comment by antonybudianto** [comment]
@Marty070 , I'll take a look at it when I'm free, thanks for the report!

**Comment by Marty070** [comment]
This fix works, thanks a lot!
